### ISSUE TITLE
outdated version

### ISSUE THREAD

**Issue by eufelipemateus** [steampoweredtaco/gotiktoklive#24]
Hello, the package version is outdated. Could you update it to the latest version available in the repository?
Here is the reference link: https://pkg.go.dev/github.com/steampoweredtaco/gotiktoklive. Versio is 30 oct 2024

**Comment by beeblebrox** [comment]
Hi there,  are you asking for the pkg.go.dev docs to be updated? Can you clarify if you mean something else?

v1.0.7 was a bad tag that never should have been pushed. However that doc package is still compatible. There should not be a tagged version yet. I am unsure how to tell pkg.go.dev to drop it, but I'll see if it is possible.

For your own code, you might have an issue if 1.0.7 is in your `go.mod` and you need to resolve it by removing the require line and running `go get github.com/steampoweredtaco/gotiktoklive@6d5c84d`  then normal updates of the modules should work as expected locally.

Please let me know if this helped you, thanks.
